### ISSUE TITLE
[PRE REVIEW]: Basicsums: A Python package for computing structural sums and the effective conductivity of random composites

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1224]
**Submitting author:** @wojciech-n (<a href="http://orcid.org/0000-0002-5475-9173">Wojciech Nawalaniec</a>)
**Repository:** <a href="https://bitbucket.org/basicsums/basicsums" target ="_blank">https://bitbucket.org/basicsums/basicsums</a>
**Version:** v1.0.0
**Editor:** @eramirem
**Reviewers:** @lucydot, @mkhorton

**Author instructions**

Thanks for submitting your paper to JOSS @wojciech-n. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@wojciech-n if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1224 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for Wojciech Nawalaniec, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@wojciech-n - please update your paper metadata `affiliation` by quoting the string.

i.e. change `affiliation: 1,2` to `affiliation: "1,2"`

```
---
title: 'Basicsums: A Python package for computing structural sums and the effective conductivity of random composites'
tags:
  - Python
  - basic sums
  - structural sums
  - computational materials science
  - pattern recognition
  - data science
authors:
  - name: Wojciech Nawalaniec
    orcid: 0000-0002-5475-9173
    affiliation: "1,2"
affiliations:
 - name: Faculty of Mathematics, Physics and Technology, Pedagogical University of Cracow
   index: 1
 - name: Materialica+ Research Group (www.materialica.plus)
   index: 2
date: 27 January 2019
bibliography: paper.bib
---
```
