### ISSUE TITLE
[PRE REVIEW]: Geometric nested sampling: sampling from distributions defined on non-trivial geometries

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1787]
**Submitting author:** @SuperKam91 (<a href="http://orcid.org/0000-0002-2089-3964">Kamran Javid</a>)
**Repository:** <a href="https://github.com/SuperKam91/gns" target ="_blank">https://github.com/SuperKam91/gns</a>
**Version:** v1.01
**Editor:** @mbobra
**Reviewers:** @ziotom78, @zhampel

**Author instructions**

Thanks for submitting your paper to JOSS @SuperKam91. **Currently, there isn't an JOSS editor assigned** to your paper.

@SuperKam91 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1787 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @SuperKam91, thanks for your interest in JOSS. Before we start our process, I noticed that while your repository contains a number of Python files, it is not structured like a formal, installable Python package.

Can you work on structuring it in this way, for example following guidelines like https://docs.python-guide.org/writing/structure/ ?

Regarding the paper, I think you need to fix the header:
```yaml
---
title: 'Geometric nested sampling'
tags:
  - Nested sampling
  - Monte Carlo methods
  - Bayesian inference
  - Astrophysics
authors:
  - name: Kamran Javid
    orcid: 0000-0002-2089-3964
    affiliation: "1, 2"
affiliations:
 - name: Astrophysics Group, Cavendish Laboratory, JJ Thomson Avenue, Cambridge CB3 0HE, UK
   index: 1
 - name: Kavli Institute for Cosmology Cambridge, Madingley Road, Cambridge, CB3 0HA, UK
   index: 2
date: 2 October 2019
bibliography: paper.bib
---

# Abstract
```
(I think the missing `---` at the end is the issue)
