### ISSUE TITLE
[PRE REVIEW]: SpeechPy - Speech Processing and Recognition

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#734]
**Submitting author:** @astorfi (<a href="http://orcid.org/0000-0003-2282-4361">Amirsina Torfi</a>)
**Repository:** <a href="https://github.com/astorfi/speechpy" target ="_blank">https://github.com/astorfi/speechpy</a>
**Version:** 2.3
**Editor:** @arfon
**Reviewers:** @ThomasA, @jjatria

**Author instructions**

Thanks for submitting your paper to JOSS @astorfi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@astorfi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #734 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:78:in `check_fields': Paper YAML header is missing expected fields: affiliations, date, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:66:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
👋@astorfi - please take a look at the submission guidelines and format your paper _exactly_ as outlined here: http://joss.theoj.org/about#paper_structure

**Comment by astorfi** [comment]
@arfon @whedon I made some modifications. Please check to see if the problem is resolved. However, the [paper.md](https://github.com/astorfi/speechpy/blob/master/paper/paper.md) file is same as before. I do not know what is the issue and what should be changed because to my view it is exactly as outlined.

**Comment by arfon** [comment]
Hi @astorfi.

Please compare this (yours):

```
---
title: 'SpeechPy - Speech Processing and Recognition'
tags:
  - Python
authors:
  - name: Amirsina Torfi
    orcid: 0000-0003-2282-4361
    affiliation: "Virginia Tech"
---
```
with this (the documented example):

```
---
title: 'Gala: A Python package for galactic dynamics'
tags:
  - Python
  - astronomy
  - dynamics
  - galactic dynamics
  - milky way
authors:
  - name: Adrian M. Price-Whelan
    orcid: 0000-0003-0872-7098
    affiliation: "1, 2" # (Multiple affiliations must be quoted)
  - name: Author 2
    orcid: 0000-0000-0000-0000
    affiliation: 2
affiliations:
 - name: Lyman Spitzer, Jr. Fellow, Princeton University
   index: 1
 - name: Institution 2
   index: 2
date: 13 August 2017
bibliography: paper.bib
---
```
